name: test
on:
  workflow_dispatch:
jobs:
   run-nightly-tests:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
           path: repo
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 2

       - name: Check Files Changed
         shell: pwsh
         id: check_file_changed
         run: |
           cd repo
           git diff --name-only HEAD^ HEAD
