name: test
on:
  workflow_dispatch:
jobs:
   run-nightly-tests:
     runs-on: ubuntu-latest
     steps:
       - name: Unzip Hypothesis Examples
         run: |
           mkdir rashul
           cd rashul
           echo "Rashul1" > r.txt 
       - name: Pushes to another repository
         id: push_directory
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
         with:
           source-directory: rashul/
           destination-github-username: 'RashulChutani'
           destination-repository-name: 'Mapping'
           user-email: rashul.chutani@gmail.com
           commit-message: Testing
           target-branch: main
