name: test
on:
  workflow_dispatch:
jobs:
   run-nightly-tests:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
           path: repo
           persist-credentials: false
           submodules: "recursive"
 
       - name: Pushes to another repository
         id: push_directory
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
         with:
           source-directory: repo/
           destination-github-username: 'RashulChutani'
           destination-repository-name: 'Mapping'
           user-email: rashul.chutani@gmail.com
           commit-message: Testing
           target-branch: main
